### ISSUE TITLE
suggestion for reducing memory usage of "blind" order trace finding.

### ISSUE THREAD

**Issue by petigura** [Keck-DataReductionPipelines/KPF-Pipeline#195]
Sounds like we were running into memory issues loading the full NEID arrays. Of course, we can always throw more memory at the problem, but if we can make this more efficient it will encourage people to develop on their own laptops. Here's an idea: 

- Open file handle
- Read the whole data into numpy array.
- Close file handle
- Bin the data in the dispersion direction by a large factor ~ 10x.
- Solve for your polynomial indeces
- Extract a cutout of the full array encapsulates order i
- Should give the same result as the full order finder. 
- Update the order finder with the full trace. 

Note: biggest memory overhead is probably the initial load of the full 2D echelle image before binning. If this is unwieldy there are ways of loading in chunks with `fitsio`, but this is probably not necessary.

**Comment by awhoward** [comment]
Closing since the KPF arrays are significantly smaller.
