### ISSUE TITLE
Naming conventions of classes

### ISSUE THREAD

**Issue by petigura** [Keck-DataReductionPipelines/KPF-Pipeline#196]
We have two main types of classes: Classes that *represent* data, e.g. 

- `kpfpipe.models.level0.KFP0` 

and classes that *operate* on data, e.g. 

- `modules.order_trace.src.order_trace.OrderTrace` or
- `modules.order_trace.src.order_trace.optimal_extraction.OptimalExtraction`. 

All of these are named as nouns, so it's hard to tell what classes *are* data and what classes *manipulate* data.

For example, from the naming conventions, it is not clear if `OrderTrace` is the order trace itself (polynomial coefficients, width, etc), or the code that computes those quantities. It is not clear if `OptimalExtraction` is the extracted spectrum or the code that computes these quantities. 

To add to my confusion, when the classes are used in the "Python like" recipe language, they are used as functions and not classes. For example, someone reading this code as Python 

```python
op_data = OptimalExtraction(*args)
```

would interpret it as constructing a new instance of the `OptimalExtraction` class and assigning that to the `op_data` variable. In reality, the recipe is doing something like this under the hood `OptimalExtraction(*args,**kwargs)._perform()`

I'm not sure what the best path forward is. One thing that would help clear things up is using verbs to name the functions that manipulate data e.g.. 

`OptimalExtraction(*args)` -> `SpectralExtractor(*args)` or `ExtractSpectrum(*args)` [my favorite]: 
`OrderTrace(*args)` -> `OrderTracer(*args)` or `TraceOrder(*args)` [my favorite]

As far as the object/functional nature of the recipe, I don't see a clean standard for both. One could break PEP8 for the classes to make the recipe look more Pythonic

```
ExtractSpectrum(*args) -> extract_spectrum(*args)
```

```python
spectrum = extract_spectrum(*args)
```

or really impress upon the reader that the usage of `TraceOrder(*args)` is not an instantiation of a class, but a shortcut of running `TraceOrder(*args)._perform()` 

We might adopt a grammar based convention four KPFDRP, e.g.

https://dev.to/somedood/a-grammar-based-naming-convention-13jf

**Comment by awhoward** [comment]
Closing this as we haven't talked about it in a while.
