### ISSUE TITLE
DRP-derived instrument-diagnostics

### ISSUE THREAD

**Issue by sblunt** [Keck-DataReductionPipelines/KPF-Pipeline#292]
Chatting with folks at SSL, the following would be useful for the instrument team:

- plot of bluest-detected etalon & LFC peaks over time, as these will shift as the fiber degrades and could indicate that the fiber needs to be replaced
- plot of LFC & etalon peak height distribution vs some "average" or "good" distribution
- alarm bell that goes off if the instrument drift (post-commissioning) deviates from expectation

I'm not sure if the DRP is the right place for this functionality, but wanted to write it down somewhere!

**Comment by awhoward** [comment]
This is part of Grafana.
