### ISSUE TITLE
Explore order-to-order stellar flux variations over time

### ISSUE THREAD

**Issue by shalverson** [Keck-DataReductionPipelines/KPF-Pipeline#394]
Compare integrated (or peak) order flux over time across echelle orders in the L1 spectra. This is helpful for understanding the performance of the ADC, and updating our atmospheric throughput model (eventually). 

Of particular interest for the commissioning data is to look at the bluest vs. the reddest orders over the several night of observations, which will tell us how well the atmospheric refraction model is doing. This is likely best done by comparing a single target to itself at a different epoch (as opposed to making target-to-target comparison).

**Comment by awhoward** [comment]
These could be summarized with a ratio of peak fluxes for a few select orders, and added to headers as a keywords.
