### ISSUE TITLE
QLP CCF plots to incorporate reweighting

### ISSUE THREAD

**Issue by bjfultn** [Keck-DataReductionPipelines/KPF-Pipeline#526]
- The mean CCF plots should incorporate the CCF weights if RWCCFRV == 'T' in the header of the RV extension
- The stacked plots should plot everything but use a light dashed line or something to distinguish orders with zero weight from those with non-zero weights

**Comment by awhoward** [comment]
@fdai-planet, was this implemented?

**Comment by fdai-planet** [comment]
yes

**Comment by awhoward** [comment]
Thanks.  Closing the Issue.
