### ISSUE TITLE
Include SKY in final RV for SoCal-Sci exposures

### ISSUE THREAD

**Issue by rrubenza** [Keck-DataReductionPipelines/KPF-Pipeline#550]
When we're operating SoCal in "Sci" mode, both the SCI and SKY fibers are illuminated with sunlight. So, we actually have four traces of solar spectrum (SCI1, SCI2, SCI3, SKY) that we can use. These exposures should be identifiable as
```
OBJECT: Sun
SCI-OBJ: Target
SKY-OBJ: Target
```
and usually (always?) CAL-OBJ = EtalonFiber. I think we can get a bit higher precision RVs if we combine all four traces for the final RV. That is, calculating CCD1RV1 (SCI1), CCD1RV2 (SCI2), CCD1RV3 (SCI3), CCD1RV4 (SKY), and the same for CCD2, and then combining all four in the same way as is done currently for RV1-3 to produce CCD1RV, CCD2RV.

**Comment by awhoward** [comment]
@cwang, is this complete?

**Comment by cwang2016** [comment]
yes, it is complete and merged to develop.
