### ISSUE TITLE
4-amplifier Red CCD images not processed correctly from L0 to 2D

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#590]
I posted this originally on Slack:  "There’s some issue with the 4-amplifier L0 used for the fast-read mode.  We’re only seeing half of the red CCD in the 2D file, and then those orders are missing in the 1D file, too.  I think the issue is in the L0 -> 2D conversion step in the DRP because I opened an L0 file in a Jupyter notebook and I can see all four quadrants.  An example frame is KP.20230612.77094.14.'

BJ responded: "It’s ignoring the other amplifiers because the red chip usually has 2"

We should fix this ASAP (days not weeks).

![jump caltech-92](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/16376935/ec85fbab-d27e-42a5-98cc-5d0b73235c62)
![jump caltech-93](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/16376935/ca3aa4d4-4486-46d6-b245-9242fbbb398d)
![jump caltech-94](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/16376935/d3820fcb-6f40-4956-b156-2a398c060a72)

**Comment by awhoward** [comment]
@RussLaher -- checking on this issue.  We're hoping to use this read mode on-sky soon (this week?) so it would be good to get it working.  

As a test, I touched the file [KP.20230612.77231.25](https://jump.caltech.edu/observing-logs/kpf/KP.20230612.77231.25) and the QLP plots still show half of the red CCD missing.

**Comment by RussLaher** [comment]
I was unaware of this issue until now.  I will look at it this afternoon.
