### ISSUE TITLE
Allow for negative flux values in L1 plots

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#594]
This is a simple change.  Could you allow for negative flux values in the L1 plots?  See the example below.  It looks like some signal is being over-subtracted and that appears as negative flux.  We should be sensitive to this.  Perhaps also draw a dashed, faint gray line at counts = 0 in each row.

![jump caltech-95](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/16376935/37afbd44-dbca-4376-8f34-2f2463e68feb)

**Comment by fdai-planet** [comment]
implemented and PR created.

https://jump.caltech.edu/observing-logs/kpf/KP.20230525.53471.19

**Comment by awhoward** [comment]
Thanks, @fdai-planet!  That was fast.
