### ISSUE TITLE
Junk status

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#603]
We mark files as 'junk' in Jump as an indication of bad data quality.  We've talked for a while about using this information in the DRP.  This Issue is an attempt to organize that effort.

The first step is to set up a system to regularly query the Jump database for all junked KPF files and put them into an ASCII file (perhaps called `kpf_junk_obsid.txt` with ObsID for entries of the form `KP.20230606.25292.14`).  This file could be as simple as a one-column ASCII file, or more complicated if there are desired features.  Keeping this ASCII file in a simple format will ensure that users of the KPF DRP who are not in the Jump ecosystem can also use the features described below.

Masters: Junked files should not be included in the construction of masters.  I can't think of any exceptions to this, but post here if you can think of any.

Other exposures: We will usually want to exclude junked files from RV time series or calibration time series.  I can see two ways to do this. First, we might configure the pipeline to not produce 2D/L1/L2 data products for junked files.  Second, we might mark junked frames in the headers of their 2D/L1/L2 data products and then allow the user/scripts to determine if junked files should be included.  I favor the second option because it allows us to examine what happens in different failure modes.

Here's one possible implementation.   

1. At regular intervals (daily?  every few hours?), a script would query the Jump database and record ObsIDs of junked files in kpf_junk_obsid.txt.  
2. The DRP should then have a mechanism to write a header keyword as early as possible (perhaps as a first step in L0->2D).  The keyword could be called JUNK with boolean possibilities.  
3. Then the master generation scripts should be modified to only include files with JUNK = False.
4. Other parts of the DRP might also be modified, but perhaps only if they affect files other than the exposures marked Junk (as Masters do).
5. Users would then adjust their analysis to account for the Junk flag.

We're going to want to distribute kpf_junk_obsid.txt to other CPS users.  Should we do this by Git-tracking the file (as we do for a few other Jump-related files; this would be in a CPS-specific repository like ) or just have it generated regularly and live in a standard place on Confluence?  I favor the first option, but it requires a little setup.

**Comment by awhoward** [comment]
Here's the Jump query in the Database Explorer: https://jump.caltech.edu/explorer/163/
Here's a direct link to a CSV file output from that query: https://jump.caltech.edu/explorer/163/download?format=csv

**Comment by awhoward** [comment]
Should junk status just be a QC criterion?

**Comment by RussLaher** [comment]
This may not be necessary because the L0Files database table has a separate status column for 0=bad and 1=good.  There is also a comment column in the record to explain why an exposure is bad.  There are currently 199 rows marked as bad (status=0) because "Filename date does not match DATE-OBS."
