### ISSUE TITLE
"manualcal" and "autocal"

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#621]
We currently have a bunch of standard calibrations whose object names start with `autocal`, e.g. `autocal-dark`, `autocal-bias`, `autocal-lfc-all-eve`.  Sometimes we like to supplement these with additional calibrations, especially for the etalon and LFC.  It would be nice to be able to label these with the `manualcal` prefix to distinguish them, but also for the pipeline to recognize them and treat them like `autocal`.

This Issue is to organize a discussion about this.  @shalverson, @bjfultn, and @RussLaher should be contributors to the discussion.

**Comment by bjfultn** [comment]
@RussLaher where is the config that defines which object names to stack in the masters recipe?

**Comment by RussLaher** [comment]
The objects are hard-wired, except for Arclamps, in kpf_masters_drp.cfg:

# Leave empty list for arclamp_objects for recipe to automatically fill in.
arclamp_objects = []

The requested capability seems straightforward, but some code changes are needed.  As noted above, we already automatically handle this for Arclamp stacks:

select dateobs,imtype,object,count(*) from l0files where object like 'manual%' group by dateobs,imtype,object order by dateobs,imtype,object;

  dateobs   | imtype  |        object        | count 
------------+---------+----------------------+-------
 2023-05-31 | Arclamp | manualcal-etalon-all |    20
(1 row)

ls -ltr /data/kpf/masters/20230531/*man*
-rw-r--r--. 1 root root 532739520 Jun  2 09:42 /data/kpf/masters/20230531/kpf_20230531_master_arclamp_manualcal-etalon-all.fits

This file was not automatically registered in the database CalFiles table, so I need to look at that, as well.

**Comment by awhoward** [comment]
@RussLaher -- could you implement this similarly for bias and dark exposures?

**Comment by RussLaher** [comment]
Yes, will do.

**Comment by RussLaher** [comment]
I also found out that /data/kpf/masters/20230531/kpf_20230531_master_arclamp_manualcal-etalon-all.fits was generated, but then the script to register it in the CalFiles database table was skipped.  So, I ran it, and now it is indeed registered in the database as expected:

select * from calfiles where startdate='2023-05-31' and level=0 and object like 'man%';
 cid  | level | caltype |        object        | contentbits | nframes |    minmjd    |    maxmjd    | infobits | startdate  |  enddate   |        
                        filename                                |             checksum             | status |         createdby          |       cr
eated       |           comment           
------+-------+---------+----------------------+-------------+---------+--------------+--------------+----------+------------+------------+--------
----------------------------------------------------------------+----------------------------------+--------+----------------------------+---------
------------+-----------------------------
 4232 |     0 | arclamp | manualcal-etalon-all |           3 |      20 | 60095.967104 | 60095.993948 |        0 | 2023-05-31 | 2023-06-01 | masters
/20230531/kpf_20230531_master_arclamp_manualcal-etalon-all.fits | 67598410b07e5e7cbbc4b0d16c4d84db |      1 | registerCalFilesForDate.py | 2023-06-
02 01:34:16 | Automated pipeline process.
(1 row)
