### ISSUE TITLE
RVs for Fast Readout Mode

### ISSUE THREAD

**Issue by bjfultn** [Keck-DataReductionPipelines/KPF-Pipeline#625]
We have 1 bad quadrant on each chip when reading out in 4 amplifier mode. There are several tests we'd like to perform in order to determine how to deal with those bad quadrants in the RVs.

1. Try nanning out sections in the 1D (L1) spectra to see what happens to the RVs and CCFs.
2. Try nanning out section sin the 2D data.
3. Try to split up the spectrum into more segments when calculating the RVs so that parts of certain orders can be omitted from the final RV calculations by the end user.

If you do not have the ability to run the pipeline in your own sandbox environment then these tests can be run by fist making a backup of a file that you want to test with. Then copy the file to somewhere locally, edit the file appropriately and return to the appropriate /data/LX/<date> directory. Let BJ know when you want to run a test and he will start an instance of the pipeline watching the particular LX directory you are working in.

**Comment by bjfultn** [comment]
The amplifier masked RVs are working for the RED chip now but we still need to determine which orders need to be masked on the GREEN chip. Assigning to @rrubenza to do or comment on what we need to perform this analysis.

**Comment by awhoward** [comment]
@rrubenza, could you comment on this?

**Comment by rrubenza** [comment]
If I'm understanding Ashley's description in slack correctly, for RED I believe it is orders 0-18 (lower half) and pixels 0-2048 (left half) for the lower-left quadrant. That is, it's the same quadrant in green and red?

![green_fsr_cti_mask](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/29154477/5d797e1b-6dc9-4616-8891-f380bc64cd8b)
![red_fsr_cti_mask](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/29154477/ae3c76c2-dba8-42be-90b7-7d98d1977ffd)
