### ISSUE TITLE
Add read noise to variance

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#635]
This can be done after the bias is measured, or perhaps we should adopt some standard read noise measurements per amplifier.

For low SNR spectra, we're not estimating the SNR properly (e.g., see below).  Other uses of KPF spectra should be using variance instead of standard deviation = sqrt(counts) for error estimation.

**Comment by awhoward** [comment]
Tagging @ashbake and @shalverson for a discussion of what the best read noise is to use for this.

**Comment by awhoward** [comment]
@RussLaher and @bjfultn -- could you remind me if this was implemented or if we just talked about it?

**Comment by RussLaher** [comment]
Yes, it has been implemented.  Database has new table called ReadNoise that is now being populated daily by the DRP for each exposure.  New module/var_exts has also been implemented in the DRP to compute variance extensions for each 2D FITS file:

 # Sum the variances for GREEN and RED chips, after converting all terms to electrons.
        # The terms in the following formulas are, respectively:
        # 1. Read-noise variance
        # 2. Master-bias variance
        # 3. Master-dark variance
        # 4. Master-flat variance
        # 5. Photon-noise variance

**Comment by RussLaher** [comment]
I still need to backfill the ReadNoise database table for all L0Files database records (there is a one-to-one correspondence).  I believe DRP reprocessing of data will take care of this (we should confirm this).

**Comment by awhoward** [comment]
Thanks, @RussLaher.  Is the read noise also being added to the variance extensions in the 2D files, which are propagated to the variance extensions in the L1 files?

**Comment by RussLaher** [comment]
Yes, that is what I tried to convey in my recent detailed comments above.

**Comment by RussLaher** [comment]
I need to do more work on module/var_exts to add checks in case GREEN_CCD or RED_CCD does not exist in the input 2D FITS file.

**Comment by awhoward** [comment]
Thanks, @RussLaher !
