### ISSUE TITLE
SKY/SCI ratio

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#642]
The ratio of SKY light to SCI light is now calculated in AnalyzeEM().  This is value is corrected for the relative efficiency and area of the Exposure Meter skiy fiber.  This should be added as a keyword to EM so that later analyses can filter on observations with a lot of sky contamination.

**Comment by bpholden** [comment]
The mini-DRP currently rescales the background EM value based on a model.
The model was from sky flat observations.

This has been part of the mini-DRP for a while, with the most recent
version implemented on April 2, 2023.

**Comment by awhoward** [comment]
Note: l plan to put this flux ratio in the FITS headers of the 2D files.
