### ISSUE TITLE
L1 data download from shrek.caltech.edu according to documentation

### ISSUE THREAD

**Issue by ghost** [Keck-DataReductionPipelines/KPF-Pipeline#670]
It looks like there aren't specific spectra files to go along with the recipe and configuration files. The documentation says the download from shrek.caltech.edu, but the site is unable to be reached. This issue was encountered when trying to access reduced L1 spectra.

**Comment by awhoward** [comment]
@ali-fazal101 -- data from KPF are distributed in two ways.  First, the Keck Observatory Archive (KOA) hosts all KPF data (and data from other instruments at the W. M. Keck Observatory).  Note that there are "proprietary periods" (18 months, typically) for spectra of stars that are part of scientific programs.  There should be many examples of stellar spectra from our "Commissioning nights" (engineering time during which we learned how to operate KPF) that don't have any proprietary period and should be available on KOA.  Also note that daily calibration spectra (bias, darks, flats, wavelength calibration spectra) should have zero proprietary period in KOA.

The second way that people access spectra is through shrek.caltech.edu or the Jump server.  This mode applies to people who are part of the California Planet Search (CPS) research group and takes some setup.

Which mode applies best to you?  Could you try to download some files from KOA?  If you get stuck, let me know and I could post some representative spectra in a public space.

Also, could you point me to the documentation that mentions shrek.caltech.edu?  Is this in one of the tutorials?  Thanks.
