### ISSUE TITLE
Add diagnostics to headers

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#733]
This Issue is to organize several notes about diagnostic information that @awhoward plans to add to the headers.  Note that these keywords should also be documented [here](https://kpf-pipeline.readthedocs.io/en/docs-pipeline-info/info/data_format.html).

- &#x2713; Dark noise (see https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/pull/729)
- &#x2713; Read noise from the overscan region.  @RussLaher - is this already in the headers or just the DB? 
- &#x2713; SNR at several wavelengths (done, but needs to be documented - See https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/issues/514).
- &#x2713; Cumulative Exposure Meter counts (see https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/issues/535)
- &#x2713; SCI/SKY flux ratio estimate of the main spectrometer from exposure meter (see analyze_em.py).
- &#x2713; Seeing estimate from a fit to the guider image (see analyze_guider.py).
- &#x2713; Guiding performance summaries (x_rms and y_rms at a minimum; other diagnostics, too?  see analyze_guider.py).
- &#x2713; CCD read speed (see kpf_parse.py)
- &#x2713; lunar separation and solar altitude (see analyze_guider.py).
- &#x2713; Flux ratios between slices (see https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/issues/351).
- &#x2713; Order-to-order flux ratios (see https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/issues/394).
- order trace drift? (see https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/issues/352)
- instrument drift (is this the cal RV?).

**Comment by RussLaher** [comment]
Read-noise keywords are now included in the PRIMARY header of the 2D FITS files.  E.g., KP.20231121.06358.42_2D.fits:

RNGREEN1=              4.85283 / Instantaneous GREEN_AMP1 read noise [electrons]
RNGREEN2=              4.14966 / Instantaneous GREEN_AMP2 read noise [electrons]
RNRED1  =               4.0376 / Instantaneous RED_AMP1 read noise [electrons]
RNRED2  =              4.12717 / Instantaneous RED_AMP2 read noise [electrons]
GREENTRT=               46.804 / GREEN chip total read time [seconds]
REDTRT  =               46.839 / RED chip total read time [seconds]
READSPED= 'regular '           / Categorization of read speed

**Comment by awhoward** [comment]
Thanks, Russ.  I'll add those headers to the documentation here: https://kpf-pipeline.readthedocs.io/en/docs-pipeline-info/info/data_format.html

**Comment by awhoward** [comment]
@RussLaher, are GREEN_AMP3 and GREEN_AMP4 read noise values computed if those amplifiers are used (for fast read mode)?   (And the same for RED.)

**Comment by RussLaher** [comment]
Yes, indeed. Read noise is computed for all amplifiers present in a given L0 FITS file.
