### ISSUE TITLE
QC: make quality control checks for exposure meter

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#741]
Some initial ideas for QC checks related to the exposure meter:

- data integrity check (is the table included as an extension when it's supposed to be)
- negative sky flux

@jonzink and @howardisaacson -- feel free to add suggested quality control checks for the EM.

**Comment by awhoward** [comment]
@shalverson -- please add your thoughts on this one, too.

**Comment by bpholden** [comment]
I would suggest checking for saturation.
There is a keyword and I can add it to the header.
NSATURD

That number is typically 0, but for some of the SoCal data it gets high.

**Comment by awhoward** [comment]
@bpholden - is NSATURD a boolean (converted to 0/1) stating whether the EM contains some number of saturated pixels?  Or is it the saturation level?

My notes say that 25,000 DN is about half of the saturation.  I've forgotten the exact saturation level though.  Is it 2^16 = 65536?

**Comment by awhoward** [comment]
That must be saturation in raw pixels, before extraction.  Any guidance on saturation in the microDRP-processed data would be appreciated.

**Comment by bpholden** [comment]
N is for number.
The saturation value is 65536. This is clear from SoCal exposures.

Josh pointed out that reporting the value once is not useful, because that
just reflects a single exposure in the stack. Ideally I would add a new
column to the table.

**Comment by bpholden** [comment]
Right now nothing is done.

In cases where it is a couple of pixels, we could either interpolate or
 reject.
In the SoCal cases, we would be rejecting most of the data.

**Comment by awhoward** [comment]
Thanks, @bpholden -- we should probably do something in the microDRP.  I don't have strong feelings the time implementation.

Looking at the saturated SoCal frames, I see a maximum of 1.93e6 counts per reduced pixel.  So we can determine how close to saturation a frame is (roughly) by dividing by that number.  That's probably a good approach for previous data, which I can implement in a quality control test.  I think this would be a good supplement to changes that @bpholden might implement.

**Comment by awhoward** [comment]
I'm working on this in the branch `feature/qc_diagnostics`

**Comment by awhoward** [comment]
@bpholden -- I'm writing a test for negative flux in the EM spectra.  Let me know what you think or if there's another algorithm that you think would be superior and is also easy to code up.  

This test will be put into a quality control method in the DRP to detect instances when the bias subtraction in the EM is too strong.  The algorithm looks for N=20 consecutive negative-flux pixels in the summed EM-SKY spectrum or the EM-SCI spectrum.  (The spectra are the sum of the EM subframes.). The idea is that negative flux can happen due to read noise in cases with very low light, but it's improbable that many pixels in a row will all have negative flux.  I set N=20 EM pixels in a row somewhat arbitrarily.  I like this algorithm because you don't have to know anything about the noise properties of the EM spectra.

The three EM-SKY spectra (red traces) below show cases where the QC test fails, barely fails, and passes this QC test.  (Pass = no significant negative flux.)

![download (75)](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/16376935/5b9dfdd6-94d9-4749-8997-851b654bb669)
![download-36](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/16376935/611904f8-a518-4396-a9ea-e3bbf46fd977)
![download (74)](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/16376935/bf8d322d-ed5a-4c46-979c-8a12838423db)

**Comment by awhoward** [comment]
PR https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/pull/755 contains new QC tests for saturation and negative flux in the reduced exposure meter spectra. A QC test for the presence of expected EM data products was already part of the QC.

I'm leaving this Issue open for now to keep the discussion going about possible improvements to the microDRP.
