### ISSUE TITLE
Establish dataset for wavelength solution experiments

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#764]
@howardisaacson to fill in details (date range, file with ObsIDs, etc.) and post them on Confluence.

**Comment by awhoward** [comment]
Note: get the telemetry (especially temperatures) for this time region.

**Comment by howardisaacson** [comment]
The time range from 24 Oct 2023 to 9 Nov 2023 (UT dates 20231024-20231109).
This Jump query: [https://jump.caltech.edu/explorer/185/](https://jump.caltech.edu/explorer/185/) can be used to find the filenames and current RVs. As the query shows, it is important to remove some ThAr frames such as those with lamp light only in the sky and/or cal fibers.
There are 294 ThAr observations available. The best green CCD RMS for this dataset for me is 5.8 m/s.

**Comment by bpholden** [comment]
Let us know if the telemetry table in the L0 file is sufficient or if you
want a full 1 Hz data table.

**Comment by awhoward** [comment]
@bpholden -- I think the telemetry table should be sufficient, at least to start.  Thanks.

**Comment by awhoward** [comment]
The Confluence page is here: https://exoplanets.atlassian.net/wiki/spaces/CPS/pages/2888761364/KPF+Test+Dataset+Alpha

Thanks, Howard.
