### ISSUE TITLE
New standard time series plots

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#783]
Here's a list of desired standard time series plots using AnalyzeTimeSeries.  These should be put onto Jump.

* etalon RV vs. time
* LFC RV vs. time
* ThAr RV vs. time
* SoCal RV vs. time
* Standard stars RV vs. time

@howardisaacson -- did I capture all of your suggestions?

**Comment by howardisaacson** [comment]
Yes, looks good!
