### ISSUE TITLE
Pipeline crash for bad IMTYPE

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KPF-Pipeline#798]
The pipeline crashed when it tried to process a bad file (one of the ones below, I'm not sure which).  A screenshot of the error is attached.  We should catch this error and find a way to proceed.

[KP.20240201.63097.08](https://jump.caltech.edu/observing-logs/kpf/KP.20240201.63097.08)
[KP.20240201.63151.50](https://jump.caltech.edu/observing-logs/kpf/KP.20240201.63151.50)

<img width="938" alt="Screenshot 2024-02-01 at 10 08 44 AM" src="https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/16376935/4e06aa82-7dfd-4219-a24b-4e9ab82791ff">

**Comment by bjfultn** [comment]
I don't really see a way to process a file without knowing what it is. Its currently crashing in the QC but if we let it go past that it will just crash somewhere else. Based on this output it looks like it just crashed for this file but continued waiting for others. Is that correct?

**Comment by awhoward** [comment]
Good points.  This Issue may be moot because Brad was able to remake the affected L0 files, and, as you say, files with this flaw may be deadends.

**Comment by bjfultn** [comment]
ok, closing this then because I think that the current behavior is what we want.
