### ISSUE TITLE
UT: 7 June 2024, wrong starname in header

### ISSUE THREAD

**Issue by howardisaacson** [Keck-DataReductionPipelines/KPF-Pipeline#915]
For the primary event on June 6th, the star name  and object name is incorrect in the header, but the RA and DEC checkout as the correct star's coordinates. The headers will need to be changed eventually to the correct star name.

**Comment by bpholden** [comment]
The problem is not in the pipeline, nor in the file assembler but in the
software that controls exposures for KPF.
That software had the wrong value.

**Comment by howardisaacson** [comment]
Thanks for fixing the files on disk Brad. I will fix the object name on our side, and the 'targname' is correct in the original files.
