### ISSUE TITLE
LFC masters are using etalon data to derive WLS

### ISSUE THREAD

**Issue by shalverson** [Keck-DataReductionPipelines/KPF-Pipeline#916]
The LFC master stacks are using etalon spectra to derive the WLS. This has been diagnosed a few ways, 1) by the SCI-OBJ keywords in the header of the LFC WLS master 2) by looking at the etalon spectrum for a given day and measuring the apparently free spectral range (the etalon line spacing is 30 GHz natively), and 3) seeing the individual LFC-calibrated orders 'shrink' in wavelength by ~30%. Since the WLS code is forcing the detected peaks in the LFC master file to be 20 GHz apart, the WLS will be compressed by a factor of 20GHz/30GHz anytime the etalon data is unintentionally used.

Examples plots showing this are below, in no particular order:

![image](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/2415196/d65eaf0c-336b-48da-9130-020a79ea0482)

<img width="1102" alt="Screenshot 2024-06-12 at 1 16 30 PM" src="https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/2415196/4505297a-69a0-418e-8350-3881280dccd5">

<img width="1424" alt="Screenshot 2024-06-12 at 1 20 00 PM" src="https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/2415196/d9ce2d18-9665-4a69-a325-d554b64f27d1">

Here's an example of what the etalon line spacing curve should look like:
![image](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/2415196/1c1119df-f7ac-47db-9388-08b355ed8d4f)

**Comment by shalverson** [comment]
In addition to fixing the masters, we also need to add some additional QCs in the WLS code to independently identify if the provided spectrum is correct or not. @aaronhouseholder  let's discuss some quick checks that we can use so that the WLS code knows not to produce a fit when it's handed the wrong source

**Comment by bjfultn** [comment]
This is an old bug that has been fixed
