### ISSUE TITLE
FITS header comments switched for science & sky SNR values

### ISSUE THREAD

**Issue by Emmavt** [Keck-DataReductionPipelines/KPF-Pipeline#934]
Following up on my conversation with @howardisaacson,  we think that the comments for the science and sky fiber SNR values might be switched in the FITS headers. For example, in the file "KP.20240617.42476.52_L1.fits" in HDU 0, the comments on the science and sky SNR values are swapped. I think this is just the case for 747nm and 852nm.

> SNRSC747= 103.1 / SNR of L1 SKY near 747 nm
> SNRSK747= 7.5 / SNR of L1 SCI (SCI1+SCI2+SCI3) near 747 nm
> SNRCL747= 6.0 / SNR of L1 CAL near 747 nm
> SNRSC852= 93.8 / SNR of L1 SKY near 852 nm
> SNRSK852= 7.8 / SNR of L1 SCI (SCI1+SCI2+SCI3) near 852 nm
> SNRCL852= 6.7 / SNR of L1 CAL near 852 nm 

It looks like the values correspond to the correct keyword, but I'm not sure if the comments are used at any stage.

**Comment by awhoward** [comment]
Thanks for pointing this out, @Emmavt.  This pull request (https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/pull/941) should fix the issue.
