### ISSUE TITLE
Add middle of night LFC to wavelength interpolation

### ISSUE THREAD

**Issue by howardisaacson** [Keck-DataReductionPipelines/KPF-Pipeline#939]
We now collect LFC cals in the middle of the night. When we observe on only first half or only second half, there are LFC calibrations labled: "autocal-lfc-all-midnight". These produce masters. 

We can add these to the wavelength interpolation setup files to shorten the time baseline between interpolations.

**Comment by bjfultn** [comment]
handled in PR #943
