### ISSUE TITLE
Pandas 1.0.4 not installing, on an M2 mac

### ISSUE THREAD

**Issue by dhritivasu** [Keck-DataReductionPipelines/KPF-Pipeline#963]
When building the docker, pandas is not installing inside the container because an error shows up saying there is no matching version. I am using a mac with an M2 chip. This is the output of the failure of the docker build. We tried to change the pandas version to 1.1.5 but that still did not work. I tried changing the python version to 3.7 since it said it requires python>=3.6.1, but the same error still occurred. 

error:

257.0 WARNING: Discarding https://files.pythonhosted.org/packages/53/87/6438c197fc70ca6b3056cfb60b3dfedca25bedb631bce1f72d6a10502d15/pandas-1.0.4.tar.gz#sha256=b35d625282baa7b51e82e52622c300a1ca9f786711b2af7cbe64f1e6831f4126 (from https://pypi.org/simple/pandas/) (requires-python:>=3.6.1). Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpe8hqlgj7 Check the logs for full command output.
257.0 ERROR: Could not find a version that satisfies the requirement pandas==1.0.4 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
257.0 ERROR: No matching distribution found for pandas==1.0.4
------

 1 warning found (use docker --debug to expand):
 - UndefinedVar: Usage of undefined variable '$PYTHONPATH' (line 9)
Dockerfile:36
--------------------
  34 |     
  35 |     ADD requirements.txt /code/KPF-Pipeline/
  36 | >>> RUN pip3 install -r requirements.txt
  37 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip3 install -r requirements.txt" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/0iz6kejt5cyp7vm5no0ore5d1

**Comment by bjfultn** [comment]
Try setting
`export DOCKER_DEFAULT_PLATFORM=linux/amd64`
in your mac's startup file.

**Comment by howardisaacson** [comment]
Thanks for the help BJ. Problem solved.
